---
- name: Install MySQL
  apt: 
    name: "{{ item }}"
    update_cache: yes 
    cache_valid_time: 3600
    state: present
  with_items:
  - python-mysqldb
  - mysql-server
  - libmysqlclient-dev
- name: Start the MySQL service
  service: 
    name: mysql 
    state: started
    enabled: true
- name: update mysql root password for all root accounts
  mysql_user: 
    name: root 
    host: "{{ item }}" 
    password: admin
    login_user: root
    login_password: admin
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

# Create a new database with name 'bobdata'
- mysql_db: name={{ application_name }} state=present login_user=root login_password=admin