---
- name: Ensure that the virtualenv file permissions are set properly
  file: path={{ virtualenv_path }}/../
        recurse=yes
        owner={{ gunicorn_user }}
        group={{ gunicorn_group }}
        state=directory
        mode='g+w'

- name: Ensure that the application file permissions are set properly
  file: path={{ project_path }}
        recurse=yes
        owner={{ gunicorn_user }}
        group={{ gunicorn_group }}
        state=directory
        mode='g+w'
  notify: restart application
