---

# Application settings.
virtualenv_path: "/vagrant/.virtualenv"
project_path: "/vagrant/{{ project_name }}"
application_path: "/vagrant/{{ application_name }}"
application_log_dir: "/var/log/{{ application_name }}/"
application_log_file: "/var/log/{{ application_name }}/gunicorn_supervisor.log"
requirements_file: "{{ project_path }}/requirements.txt"


# Gunicorn settings
gunicorn_user: vagrant
gunicorn_group: vagrant
upstream_addr: 127.0.0.1:8080

# Nginx settings
nginx_http_port: 80
nginx_https_port: 443
nginx_access_log_file: "{{ application_log_dir }}/nginx_access.log"
nginx_error_log_file: "{{ application_log_dir }}/nginx_error.log"
nginx_static_dir: "{{ project_path }}/static/"
nginx_media_dir: "{{ project_path }}/media/"

# Django Environment variables
django_environment:
  DJANGO_SETTINGS_MODULE: "{{ django_settings_file }}"
  DJANGO_SECRET_KEY: "{{ django_secret_key }}"
  EMAIL_HOST: "{{ smtp_host }}"
  EMAIL_HOST_USER: "{{ smtp_user }}"
  EMAIL_HOST_PASSWORD: "{{ smtp_password }}"
  DATABASE_USER: "{{ db_user }}"
  DATABASE_PASSWORD: "{{ db_password }}"
